### ISSUE TITLE
Finalize Travis CI Integration

### ISSUE THREAD

**Issue by alyptik** [Lind-Project/native_client#1]
The current goal is to have this repository auto-trigger builds at the main Travis CI instance [[1]](https://travis-ci.org/Lind-Project/lind_project/settings) when commits are pushed.

[1] [https://travis-ci.org/Lind-Project/lind_project/settings](https://travis-ci.org/Lind-Project/lind_project/settings)

**Comment by alyptik** [comment]
Webhooks should be triggering automated builds on pushes now.

**Comment by alyptik** [comment]
This is still something that should be revisited at some point, as a working CI would be very useful to have.

**Comment by lukpueh** [comment]
I created [this little Flask webapp](https://gist.github.com/lukpueh/498ff3489321bdc7106c05a2fd5b941c) that listens for push notifications on the `native_client` repo (1) originating from a [GitHub webhook](https://developer.github.com/webhooks/) and makes a call to the [Travis API](https://docs.travis-ci.com/user/triggering-builds/) to  trigger a build on the `lind_project` repo (2).

Feel free to adopt and use it as you see fit. Alternatively, I can set it up for you, if you give me admin access to the Lind project organization. :)

One thing I'm not so sure about is how (1) and (2) are related. I see that you have a bunch of submodules in (2), but none of them point to (1), right?

So in order for this webhook to make sense, a change in (1) should somehow propagate to (2).

**Comment by alyptik** [comment]
Sorry was a bit busy over the weekend, sent you the invite @lukpueh, thanks!

**Comment by lukpueh** [comment]
Thanks, @alyptik. Before I set anything up though, we should discuss the questions I have. Either here and/or later today during the dev meeting.

**Comment by alyptik** [comment]
@lukpueh Hope that kind of explained things a bit, if you have any other questions feel free to email me

**Comment by lukpueh** [comment]
Okay, so from our discussion on Tuesday I gathered that, when building `Lind-project/lind_project` it git clones `Lind-project/native_client` at branch `develop`  (see [mklind#L190](https://github.com/Lind-Project/lind_project/blob/master/mklind#L190) and [mklind#L296-L297](https://github.com/Lind-Project/lind_project/blob/master/mklind#L296-L297)).

In order for the proposed trigger-push-via-webhook setup to be effective the  hardcoded `develop` branch in [mklind#L190](https://github.com/Lind-Project/lind_project/blob/master/mklind#L190) would need to be changed to the commit id being pushed before building.

The GitHub [webhook does send the commit id](https://gist.github.com/lukpueh/498ff3489321bdc7106c05a2fd5b941c#file-lind_webhook_listener-py-L54) that's being pushed, so we could pass it on to Travis CI in the [API call](https://gist.github.com/lukpueh/498ff3489321bdc7106c05a2fd5b941c#file-lind_webhook_listener-py-L68-L72), e.g. setting a Travis environment variable that is read by `mklind` to override the pointer to the `develop` branch.

I don't really like that approach as it builds `lind_project` with a version of `native_client` that is not defined in the `lind_project` codebase but magically set on the Travis server.

We could do some more webhook sorcery, e.g. listen for pushes to `native_client` and dynamically change and commit the reference in `lind_project` and push it to a dedicated branch, which would also trigger a build.


*Addendum:*
An alternative to cloning `native_client` in `mklind` would be to add `native_client` as a submodule. But this would still require actively updating the submodule reference in `lind_project` on a push to the submodule, akin to telling `mklind` to clone the dependency at a certain commit.

There's also an alternative solution to GitHub webhooks with a custom listening endpoint. That is, specifying a travis build routine for `native_client` whose only purpose is to trigger the build for `lind_project` using the Travis API (see [this example](http://blog.mesouug.com/2017/03/07/github-travis-ci-submodule-trigger-build-for-main-project/)).

**Comment by alyptik** [comment]
@lukpueh Hm, I'm currently seeing if I can just `git submodule` the native_client repository, and merge all the dependencies into the main repository with `git subtree`. Would that make this a bit easier you think?

**Comment by lukpueh** [comment]
As mentioned above, it does not eliminate the need to update the submodule on a push, so that the supermodule is built with the updated submodule.

So no, it does not make building lind_project on a push to native_client any easier. I do think however that it would make the relationship more transparent.

**Comment by JustinCappos** [comment]
We should discuss in the developers' meeting.  In general, we want to use
similar git features / setup across projects unless there is a good reason
not to.

**Comment by alyptik** [comment]
@lukpueh Since `native_client` is a submodule now, [mklind#L235](https://github.com/Lind-Project/lind_project/blob/master/mklind#L235) should update the submodule reference when the webhook triggers the build to run `./mklind` shouldn't it?

**Comment by alyptik** [comment]
@JustinCappos Yeah, so then I think making it a submodule is for the best, since that's what our other projects do. After shifting a few things around it does seem to be a lot cleaner in general doing it this way too.

**Comment by JustinCappos** [comment]
Okay, that's fine.  It's more that I want to be sure that someone coming in
doesn't need to learn 5 different git oddities to handle similar cases.
